export type Service = {
  slug: string;
  name: string;
  tagline: string;
  category: string;
  categorySlug: string;
  icon: string;
  color: string;
  overview: string;
  features: string[];
  technologies: string[];
  process: string[];
  targetAudience: string;
};

export type ServiceCategory = {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  color: string;
  services: Service[];
};

export const serviceCategories: ServiceCategory[] = [
  {
    slug: "erp",
    name: "ERP & Business Solutions",
    shortName: "ERP",
    description:
      "Enterprise resource planning and business management systems that unify your operations, automate workflows, and give you real-time visibility across every department.",
    icon: "Database",
    color: "#00d4ff",
    services: [
      {
        slug: "odoo-implementation",
        name: "Odoo ERP Implementation & Customization",
        tagline: "Full-lifecycle Odoo 18 Enterprise deployment for UAE businesses",
        category: "ERP & Business Solutions",
        categorySlug: "erp",
        icon: "Settings2",
        color: "#00d4ff",
        overview:
          "End-to-end Odoo 18 Enterprise deployment covering all core modules — CRM, Sales, Purchase, Inventory, Manufacturing, Accounting, HR, Payroll, Project Management, Helpdesk, and eCommerce. We handle everything from initial business analysis and gap assessment through data migration from legacy systems (SAP, Oracle, QuickBooks, Tally), custom module development, Odoo Studio customizations, third-party integrations, and post-go-live managed support. Our certified Odoo consultants have delivered 80+ successful implementations across the UAE.",
        features: [
          "Full lifecycle implementation — analysis to go-live",
          "Data migration from SAP, Oracle, QuickBooks, Tally",
          "Custom Python module development",
          "Odoo Studio visual customizations",
          "UAE VAT compliance & Arabic localization",
          "Multi-company & multi-currency setup",
          "Government portal integrations (FTA, MOHRE, ICP)",
          "Biometric attendance & payroll integration",
          "User training & change management",
          "SLA-backed managed post-go-live support",
        ],
        technologies: [
          "Odoo 18 Enterprise",
          "Python",
          "PostgreSQL",
          "XML / QWeb",
          "REST APIs",
          "Odoo Studio",
          "Docker",
          "nginx",
        ],
        process: [
          "Business Analysis",
          "Gap Assessment",
          "Solution Design",
          "Development & Config",
          "Data Migration",
          "UAT & Training",
          "Go-Live",
          "Managed Support",
        ],
        targetAudience:
          "SMEs and enterprises looking to centralize operations on a modern, cost-effective ERP platform. Ideal for companies with 20–5000+ employees across any industry.",
      },
      {
        slug: "odoo-hcm",
        name: "Odoo Human Capital Management",
        tagline: "Complete HR digital transformation with UAE labor law compliance",
        category: "ERP & Business Solutions",
        categorySlug: "erp",
        icon: "Users",
        color: "#00d4ff",
        overview:
          "Complete HR digital transformation on Odoo — from WPS-compliant payroll processing to performance management, learning management, and employee self-service. We build end-to-end people management workflows including separation/exit forms, company loans, advance salary, provident fund, biometric attendance integration, leave management with UAE public holiday calendars, automated HR letter generation, and end-of-service gratuity calculation per UAE labor law (Federal Decree-Law No. 33 of 2021).",
        features: [
          "WPS-compliant payroll processing & SIF file generation",
          "End-of-service gratuity (UAE labor law compliant)",
          "Performance appraisal with KPIs & OKRs",
          "Learning Management System (LMS)",
          "Employee & Manager Self-Service portals",
          "Biometric attendance integration (ZKTeco, Suprema)",
          "Leave management with UAE public holiday rules",
          "Company loan & advance salary workflows",
          "Succession planning & talent mapping",
          "Travel & expense management",
          "Automated HR letter & document generation",
          "MOHRE & GPSSA compliance",
        ],
        technologies: [
          "Odoo 18 HR Suite",
          "Python",
          "ZKTeco / Suprema APIs",
          "WPS SIF Generator",
          "MOHRE Integration",
          "GPSSA Integration",
          "Biometric SDKs",
        ],
        process: [
          "HR Process Audit",
          "Requirements Mapping",
          "Configuration",
          "Custom Development",
          "Payroll Setup",
          "Integration",
          "Training",
          "Go-Live",
        ],
        targetAudience:
          "Companies with 50–5000+ employees needing modern HR automation with full UAE labor law compliance and government portal integration.",
      },
      {
        slug: "odoo-crm",
        name: "Odoo CRM & Marketing Automation",
        tagline: "Multi-channel lead capture to closed deal — fully tracked",
        category: "ERP & Business Solutions",
        categorySlug: "erp",
        icon: "TrendingUp",
        color: "#00d4ff",
        overview:
          "Transform your sales pipeline with Odoo CRM enhanced by multi-channel lead capture (website forms, WhatsApp, social media, Google Ads, Meta Lead Ads), intelligent round-robin lead assignment, GCLID/UTM tracking for full ad attribution, pipeline automation, email marketing campaigns, and integrated reporting dashboards. Achieve complete visibility from ad click to closed deal with automated CRM workflows and real-time lead scoring.",
        features: [
          "Multi-channel lead capture (web, WhatsApp, social)",
          "Round-robin lead assignment by channel & team",
          "Google Ads GCLID → CRM attribution tracking",
          "Meta Lead Ads webhook integration",
          "WhatsApp Business API (SleekFlow/Twilio)",
          "UTM parameter tracking (source, medium, campaign)",
          "Automated email nurturing sequences",
          "Pipeline stage automation & lead scoring",
          "Custom dashboards & sales reporting",
          "Zapier & webhook integrations",
          "SMS & voice campaign integrations",
        ],
        technologies: [
          "Odoo CRM",
          "Python",
          "Google Ads API",
          "Meta Marketing API",
          "SleekFlow / Twilio",
          "Zapier",
          "REST APIs",
          "PostgreSQL",
        ],
        process: [
          "Sales Process Analysis",
          "CRM Configuration",
          "Lead Channel Setup",
          "Integration Development",
          "Attribution Setup",
          "Team Training",
          "Go-Live & Optimization",
        ],
        targetAudience:
          "Sales-driven businesses wanting full visibility and automation from ad click to closed deal, with multi-channel lead management.",
      },
      {
        slug: "sap-business-one",
        name: "SAP Business One Implementation",
        tagline: "Enterprise-grade ERP for mid-market businesses",
        category: "ERP & Business Solutions",
        categorySlug: "erp",
        icon: "BarChart3",
        color: "#0099cc",
        overview:
          "Enterprise-grade ERP implementation for mid-market businesses on the SAP ecosystem. Full deployment, customization, integration, and ongoing support for SAP Business One across financials, sales, purchasing, inventory, production, and analytics. Our SAP-certified consultants ensure seamless deployment with minimal business disruption.",
        features: [
          "Full SAP B1 implementation & configuration",
          "Financial management & reporting",
          "Warehouse & inventory management",
          "Production planning & MRP",
          "Crystal Reports customization",
          "SAP HANA analytics & reporting",
          "Third-party API integrations",
          "Data migration from legacy systems",
          "User training & documentation",
          "Ongoing support & optimization",
        ],
        technologies: [
          "SAP Business One",
          "SAP HANA",
          "Crystal Reports",
          "SQL Server",
          "DI API",
          "Service Layer API",
          ".NET",
        ],
        process: [
          "Requirements Analysis",
          "Solution Blueprint",
          "Configuration",
          "Custom Development",
          "Data Migration",
          "Testing & UAT",
          "Go-Live & Support",
        ],
        targetAudience:
          "Mid-market enterprises (50–500 employees) requiring SAP ecosystem compliance, parent company mandates, or enterprise-scale financial management.",
      },
      {
        slug: "zoho-suite",
        name: "Zoho ERP & CRM Suite",
        tagline: "Cost-effective cloud business management for UAE SMEs",
        category: "ERP & Business Solutions",
        categorySlug: "erp",
        icon: "Cloud",
        color: "#e74c3c",
        overview:
          "Complete Zoho One, Zoho CRM, Zoho Books, and Zoho People implementation for SMEs wanting cost-effective cloud ERP. Configuration, customization with Deluge scripting, workflow automation, UAE VAT compliance in Zoho Books, and third-party integrations. We handle full data migration and team training.",
        features: [
          "Zoho One unified platform setup",
          "Zoho CRM pipeline & automation",
          "Zoho Books (UAE VAT compliance)",
          "Zoho People HRMS configuration",
          "Deluge scripting for custom workflows",
          "Zoho Analytics dashboards",
          "Third-party integrations (payments, shipping)",
          "Data migration from legacy systems",
          "Arabic localization",
          "User training & support",
        ],
        technologies: [
          "Zoho One",
          "Zoho CRM",
          "Zoho Books",
          "Zoho People",
          "Deluge Script",
          "REST APIs",
          "Zapier",
        ],
        process: [
          "Process Assessment",
          "Platform Configuration",
          "Custom Scripting",
          "Integration Setup",
          "Data Migration",
          "Training",
          "Go-Live",
        ],
        targetAudience:
          "SMEs and startups (5–100 employees) wanting affordable, cloud-native business management with fast deployment timelines.",
      },
      {
        slug: "dynamics-365",
        name: "Microsoft Dynamics 365",
        tagline: "Microsoft ecosystem CRM & ERP for enterprise operations",
        category: "ERP & Business Solutions",
        categorySlug: "erp",
        icon: "Layers",
        color: "#0078d4",
        overview:
          "CRM & ERP implementation for enterprises embedded in the Microsoft ecosystem. Dynamics 365 Sales, Customer Service, Finance, Supply Chain — fully integrated with Microsoft 365, Power Platform, and Azure. Custom development in C# and .NET with Power Automate workflows and Power BI dashboards.",
        features: [
          "Dynamics 365 Sales & Customer Service",
          "Finance & Operations implementation",
          "Supply Chain Management",
          "Power Automate workflow automation",
          "Power BI dashboards & analytics",
          "Microsoft 365 integration",
          "Azure cloud services integration",
          "Custom development (C#, .NET)",
          "Teams integration for collaboration",
          "AI Copilot features",
        ],
        technologies: [
          "Dynamics 365",
          "Power Platform",
          "Azure",
          "C# / .NET",
          "Power BI",
          "Power Automate",
          "Microsoft 365",
        ],
        process: [
          "Business Analysis",
          "Solution Architecture",
          "Configuration",
          "Custom Development",
          "Data Migration",
          "Testing",
          "Go-Live & Support",
        ],
        targetAudience:
          "Enterprises (200+ employees) requiring Microsoft ecosystem alignment, parent company mandates, or tight Microsoft 365 integration.",
      },
      {
        slug: "custom-erp",
        name: "Custom ERP Development",
        tagline: "Bespoke ERP built precisely for your unique workflows",
        category: "ERP & Business Solutions",
        categorySlug: "erp",
        icon: "Code2",
        color: "#7b2fff",
        overview:
          "Bespoke ERP solutions built from the ground up for businesses with unique operational workflows that off-the-shelf platforms cannot serve. Full custom architecture, design, development, and deployment using modern cloud-native technologies. Microservices architecture, API-first design, and role-based access control built for scale.",
        features: [
          "Custom architecture design & planning",
          "Tailored to unique business processes",
          "Scalable microservices architecture",
          "Role-based access control (RBAC)",
          "Custom reporting & business intelligence",
          "API-first design for integrations",
          "Mobile-responsive progressive web app",
          "Cloud-native deployment (AWS/Azure)",
          "Real-time notifications & alerts",
          "Multi-tenant & multi-company support",
        ],
        technologies: [
          "Next.js / React",
          "Node.js / Python",
          "PostgreSQL / MongoDB",
          "Redis",
          "Docker / Kubernetes",
          "AWS / Azure",
          "GraphQL / REST",
        ],
        process: [
          "Discovery Workshop",
          "System Architecture",
          "UI/UX Design",
          "Sprint Development",
          "QA & Testing",
          "Deployment",
          "Training & Handover",
          "Ongoing Support",
        ],
        targetAudience:
          "Businesses with highly specialized workflows, proprietary processes, or regulatory requirements that off-the-shelf ERP platforms cannot accommodate.",
      },
    ],
  },
  {
    slug: "web-ecommerce",
    name: "Web & eCommerce Development",
    shortName: "Web & eCommerce",
    description:
      "From stunning corporate websites to high-converting eCommerce stores — built with cutting-edge technology, optimized for performance, and designed to grow your business.",
    icon: "Globe",
    color: "#00e68a",
    services: [
      {
        slug: "custom-websites",
        name: "Custom Website Design & Development",
        tagline: "Award-worthy custom websites that convert visitors into clients",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "Monitor",
        color: "#00e68a",
        overview:
          "Custom Next.js, React, and Vue.js websites built with performance-first architecture. Corporate websites, landing pages, portals, and microsites with EN/AR RTL support, WCAG 2.1 AA accessibility, comprehensive SEO architecture, and headless CMS integration (Sanity, Strapi, WordPress headless). Every project is Core Web Vitals optimized targeting 95+ Lighthouse scores.",
        features: [
          "Custom UI/UX design (Figma to pixel-perfect code)",
          "Next.js 16 / React with App Router & RSC",
          "EN/AR bilingual with RTL layout switching",
          "WCAG 2.1 AA accessibility compliance",
          "Core Web Vitals optimization (95+ Lighthouse)",
          "Headless CMS integration (Sanity/Strapi)",
          "GSAP & Motion animations",
          "SEO architecture with JSON-LD structured data",
          "GA4 + GTM analytics setup",
          "Vercel/AWS deployment & CDN",
        ],
        technologies: [
          "Next.js 16",
          "TypeScript",
          "Tailwind CSS",
          "GSAP",
          "Motion",
          "Sanity / Strapi",
          "Vercel",
        ],
        process: [
          "Discovery & Strategy",
          "UI/UX Design",
          "Design Review",
          "Development",
          "CMS Setup",
          "Testing & QA",
          "Launch",
          "Support",
        ],
        targetAudience:
          "Businesses needing a premium digital presence that reflects their brand quality and converts visitors into leads and customers.",
      },
      {
        slug: "wordpress",
        name: "WordPress Development",
        tagline: "Powerful, flexible WordPress sites built for performance",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "FileText",
        color: "#21759b",
        overview:
          "Custom WordPress themes, plugins, and WooCommerce stores built with performance and security as priorities. Elementor/Gutenberg block development, multisite setups, security hardening, speed optimization with 95+ Lighthouse scores, and full data migrations from other platforms.",
        features: [
          "Custom theme development from Figma",
          "Custom plugin development",
          "WooCommerce store setup & customization",
          "Elementor / Gutenberg block development",
          "WordPress multisite configuration",
          "Security hardening & malware protection",
          "Speed optimization (95+ Lighthouse)",
          "Migrations from Wix, Squarespace, other CMS",
          "Arabic RTL support",
          "Ongoing maintenance plans",
        ],
        technologies: [
          "WordPress",
          "PHP",
          "WooCommerce",
          "Elementor",
          "ACF / CPT",
          "Cloudflare",
          "WP Rocket",
        ],
        process: [
          "Requirements",
          "Design",
          "Theme Development",
          "Plugin Setup",
          "Content Migration",
          "Testing",
          "Launch",
        ],
        targetAudience:
          "Businesses needing a content-managed website with familiar admin interfaces, WooCommerce stores, or migrating from outdated platforms.",
      },
      {
        slug: "shopify",
        name: "Shopify & Shopify Plus Development",
        tagline: "High-converting Shopify stores built for GCC eCommerce",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "ShoppingBag",
        color: "#96bf48",
        overview:
          "Complete Shopify and Shopify Plus store development — from custom Liquid theme creation to headless Shopify with Hydrogen/Oxygen. UAE/GCC optimized with multi-currency, Arabic RTL, local payment gateways (Network International, Tabby, Tamara BNPL), and CRO-focused UX design.",
        features: [
          "Custom Liquid theme development",
          "Shopify Plus custom checkout & scripts",
          "Headless Shopify (Hydrogen / Oxygen)",
          "UAE payment gateways (Network Int'l, Tabby, Tamara)",
          "Multi-currency & multi-language (EN/AR)",
          "Shopify POS integration",
          "App development & customization",
          "ERP integration (Odoo, SAP, NetSuite)",
          "CRO-focused UX & A/B testing",
          "Migration from WooCommerce / Magento",
        ],
        technologies: [
          "Shopify / Shopify Plus",
          "Liquid",
          "Hydrogen",
          "React",
          "Shopify APIs",
          "Tabby / Tamara APIs",
          "Network International",
        ],
        process: [
          "Store Strategy",
          "Theme Design",
          "Development",
          "App Integration",
          "Payment Setup",
          "Testing",
          "Launch & CRO",
        ],
        targetAudience:
          "Retail brands and eCommerce businesses targeting UAE/GCC consumers, needing a fast-launching, conversion-optimized online store.",
      },
      {
        slug: "magento",
        name: "Magento / Adobe Commerce",
        tagline: "Enterprise eCommerce for high-volume UAE retailers",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "Store",
        color: "#f46f25",
        overview:
          "Enterprise-grade Adobe Commerce (Magento 2) implementation for high-volume retailers and B2B portals. Custom extension development, complex catalog management, ERP integration, and performance tuning for UAE market requirements.",
        features: [
          "Magento 2 / Adobe Commerce implementation",
          "Custom extension development",
          "B2B portal configuration",
          "Complex product catalog management",
          "ERP / OMS integration",
          "Performance optimization (caching, CDN)",
          "Multi-store & multi-language setup",
          "Payment gateway integration",
          "Security patches & upgrades",
          "PWA Storefront development",
        ],
        technologies: [
          "Magento 2 / Adobe Commerce",
          "PHP",
          "MySQL",
          "Elasticsearch",
          "Redis",
          "Varnish",
          "AWS",
        ],
        process: [
          "Commerce Strategy",
          "Architecture Design",
          "Development",
          "Integration",
          "Performance Testing",
          "UAT",
          "Launch",
        ],
        targetAudience:
          "Large retailers and B2B companies with complex catalog, pricing, and fulfillment requirements needing enterprise-grade eCommerce.",
      },
      {
        slug: "woocommerce",
        name: "WooCommerce Development",
        tagline: "WordPress eCommerce with UAE payment & shipping integrations",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "ShoppingCart",
        color: "#96588a",
        overview:
          "WordPress + WooCommerce stores optimized for UAE eCommerce — with local payment gateways (Network International, Tabby, Tamara BNPL, Stripe, PayTabs), UAE shipping integrations (Aramex, Fetchr, SMSA), Arabic RTL support, and performance optimization.",
        features: [
          "Custom WooCommerce theme development",
          "UAE payment gateways (Tabby, Tamara, PayTabs)",
          "Shipping integrations (Aramex, Fetchr, SMSA)",
          "Arabic RTL & bilingual support",
          "Custom checkout optimization",
          "Product configurators & variations",
          "Subscription & membership systems",
          "Inventory management integration",
          "Abandoned cart recovery",
          "Speed optimization (95+ Lighthouse)",
        ],
        technologies: [
          "WooCommerce",
          "WordPress",
          "PHP",
          "Tabby / Tamara",
          "Aramex API",
          "PayTabs",
          "Redis",
        ],
        process: [
          "Store Planning",
          "Design",
          "Development",
          "Payment Setup",
          "Shipping Config",
          "Testing",
          "Launch",
        ],
        targetAudience:
          "SME retailers wanting a cost-effective, fully-featured eCommerce store with UAE-specific payment and logistics integrations.",
      },
      {
        slug: "headless-commerce",
        name: "Headless Commerce",
        tagline: "Composable commerce for maximum performance & flexibility",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "Zap",
        color: "#ff6b35",
        overview:
          "Composable commerce architectures using best-in-class headless platforms (Medusa.js, Saleor, commercetools) with blazing-fast Next.js or Remix storefronts. Decoupled architecture enables independent scaling, faster deployments, and superior performance.",
        features: [
          "Medusa.js / Saleor / commercetools backend",
          "Next.js / Remix custom storefront",
          "Edge-deployed for global performance",
          "Microservices architecture",
          "Custom checkout experiences",
          "Omnichannel commerce (web, mobile, POS)",
          "Real-time inventory & pricing APIs",
          "Headless CMS integration",
          "A/B testing infrastructure",
          "99.9% uptime SLA",
        ],
        technologies: [
          "Medusa.js / Saleor",
          "Next.js / Remix",
          "TypeScript",
          "GraphQL",
          "Redis",
          "PostgreSQL",
          "Vercel Edge",
        ],
        process: [
          "Commerce Architecture",
          "Platform Selection",
          "Backend Setup",
          "Storefront Development",
          "Integration",
          "Performance Testing",
          "Launch",
        ],
        targetAudience:
          "High-traffic retailers and DTC brands needing maximum performance, flexibility, and the ability to sell across multiple channels simultaneously.",
      },
      {
        slug: "ui-ux-design",
        name: "UI/UX Design",
        tagline: "Research-driven design that converts and delights users",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "Palette",
        color: "#e91e8c",
        overview:
          "User-centered design services from research to final Figma prototypes. User research, competitive analysis, information architecture, wireframing, visual design, interactive prototyping, usability testing, and design system creation for web and mobile applications.",
        features: [
          "User research & persona development",
          "Competitive & heuristic analysis",
          "Information architecture & sitemaps",
          "Wireframing & low-fidelity prototypes",
          "High-fidelity Figma design",
          "Interactive prototype & micro-animations",
          "Design system & component library",
          "Usability testing & iteration",
          "Accessibility design (WCAG 2.1 AA)",
          "Handoff documentation for developers",
        ],
        technologies: [
          "Figma",
          "FigJam",
          "Maze / UserTesting",
          "Hotjar",
          "Adobe CC",
          "Principle",
          "ProtoPie",
        ],
        process: [
          "Discovery & Research",
          "Ideation",
          "Wireframes",
          "Visual Design",
          "Prototyping",
          "Usability Testing",
          "Handoff",
        ],
        targetAudience:
          "Businesses building new digital products or redesigning existing ones who want data-driven design decisions and pixel-perfect execution.",
      },
      {
        slug: "odoo-ecommerce",
        name: "Odoo eCommerce",
        tagline: "Native Odoo store with full ERP backend integration",
        category: "Web & eCommerce Development",
        categorySlug: "web-ecommerce",
        icon: "Package",
        color: "#714b67",
        overview:
          "Native Odoo Website + eCommerce module implementation fully integrated with your Odoo ERP backend. Real-time inventory, unified customer data, and seamless order management without third-party sync. UAE payment gateway integrations and Arabic RTL support.",
        features: [
          "Odoo Website & eCommerce setup",
          "Real-time inventory synchronization",
          "Unified CRM & customer data",
          "UAE payment gateway integration",
          "Arabic RTL storefront",
          "Custom product configurators",
          "B2B portal with pricelist rules",
          "Shipping integration (Aramex, Fetchr)",
          "Automated order-to-fulfillment workflow",
          "Customer portal & self-service",
        ],
        technologies: [
          "Odoo 18",
          "Python",
          "QWeb",
          "PostgreSQL",
          "Stripe / PayTabs",
          "Aramex API",
          "Odoo Studio",
        ],
        process: [
          "ERP Assessment",
          "Store Design",
          "Module Config",
          "Payment Setup",
          "Integration Testing",
          "Training",
          "Launch",
        ],
        targetAudience:
          "Existing Odoo users wanting to add eCommerce without third-party sync complexity, or new businesses wanting unified ERP + eCommerce.",
      },
    ],
  },
  {
    slug: "digital-marketing",
    name: "Digital Marketing & Creative",
    shortName: "Marketing",
    description:
      "Full-funnel digital marketing strategies that drive real business results — from search visibility to brand-defining creative that makes you unforgettable.",
    icon: "Megaphone",
    color: "#c9a44c",
    services: [
      {
        slug: "seo",
        name: "Search Engine Optimization (SEO)",
        tagline: "Dominate Google rankings in UAE & GCC markets",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Search",
        color: "#c9a44c",
        overview:
          "Comprehensive SEO strategy covering technical optimization, content strategy, link building, and local SEO for UAE and GCC markets. We combine data-driven keyword research with authoritative content creation to drive sustainable organic traffic growth that compounds over time.",
        features: [
          "Technical SEO audit & remediation",
          "UAE/GCC keyword research & mapping",
          "On-page optimization & content strategy",
          "Google Business Profile optimization",
          "Local SEO for Dubai & UAE cities",
          "Link building & digital PR",
          "Core Web Vitals optimization",
          "Schema markup implementation",
          "Competitor analysis & gap identification",
          "Monthly reporting & ROI tracking",
        ],
        technologies: [
          "Ahrefs",
          "SEMrush",
          "Google Search Console",
          "Screaming Frog",
          "Surfer SEO",
          "GA4",
          "Looker Studio",
        ],
        process: [
          "SEO Audit",
          "Keyword Strategy",
          "Technical Fixes",
          "Content Plan",
          "Link Building",
          "Monthly Reporting",
          "Optimization",
        ],
        targetAudience:
          "Businesses wanting to reduce dependence on paid ads and build long-term organic visibility in UAE and GCC search results.",
      },
      {
        slug: "google-ads",
        name: "Google Ads & SEM",
        tagline: "High-ROI paid search campaigns for UAE businesses",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Target",
        color: "#4285f4",
        overview:
          "Full-service Google Ads management including Search, Display, Shopping, YouTube, and Performance Max campaigns. We specialize in UAE market targeting with Arabic & English ad copy, competitive bidding strategies, and conversion tracking integrated with your CRM for full attribution.",
        features: [
          "Google Search, Display & Shopping campaigns",
          "Performance Max campaigns",
          "YouTube video advertising",
          "Arabic & English ad copy creation",
          "UAE geo-targeting & audience segmentation",
          "Conversion tracking & CRM integration",
          "GCLID to CRM attribution",
          "Landing page design & CRO",
          "Competitor analysis & bid strategy",
          "Google Merchant Center setup",
        ],
        technologies: [
          "Google Ads",
          "Google Merchant Center",
          "GA4",
          "Google Tag Manager",
          "Looker Studio",
          "Optmyzr",
          "Unbounce",
        ],
        process: [
          "Account Audit",
          "Campaign Strategy",
          "Ad Creation",
          "Campaign Launch",
          "Bid Optimization",
          "CRO",
          "Monthly Reporting",
        ],
        targetAudience:
          "Businesses needing immediate, measurable lead generation with clear ROI tracking across UAE and GCC markets.",
      },
      {
        slug: "social-media",
        name: "Social Media Marketing",
        tagline: "Authentic brand stories that build community and drive growth",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Share2",
        color: "#e1306c",
        overview:
          "Organic social media management for UAE brands — content strategy, creative production, community management, and growth across Instagram, LinkedIn, TikTok, X (Twitter), and Snapchat. Arabic & English content with UAE-first cultural relevance.",
        features: [
          "Multi-platform strategy (IG, LinkedIn, TikTok, X)",
          "Arabic & English content creation",
          "Professional photography & videography",
          "Reels, Stories & TikTok short-form video",
          "Community management & DM responses",
          "Influencer identification & collaboration",
          "Content calendar planning",
          "Brand voice development",
          "Hashtag strategy & trend hijacking",
          "Monthly analytics & performance reports",
        ],
        technologies: [
          "Later / Hootsuite",
          "Canva Pro / Adobe CC",
          "CapCut / Premiere Pro",
          "Sprout Social",
          "Meta Business Suite",
          "TikTok Business Center",
        ],
        process: [
          "Brand Audit",
          "Strategy",
          "Content Calendar",
          "Production",
          "Publishing",
          "Community Mgmt",
          "Reporting",
        ],
        targetAudience:
          "Brands wanting to build genuine social media presence, grow engaged communities, and convert followers into customers.",
      },
      {
        slug: "paid-social",
        name: "Meta & Social Media Advertising",
        tagline: "Precision-targeted social ads that fill your pipeline",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Radio",
        color: "#0866ff",
        overview:
          "Performance-driven Meta (Facebook/Instagram), TikTok, LinkedIn, Snapchat, and X advertising with creative strategy, audience segmentation, and CRM integration. We specialize in UAE audience targeting with conversion-optimized creatives in Arabic and English.",
        features: [
          "Meta (FB/IG) campaign strategy & management",
          "TikTok Ads for UAE/GCC markets",
          "LinkedIn B2B advertising",
          "Snapchat Ads for GCC audience",
          "Arabic & English creative production",
          "Meta Pixel & Conversions API setup",
          "Custom & lookalike audience building",
          "Lead Ads with CRM webhook integration",
          "Retargeting campaign architecture",
          "Creative testing (A/B & multivariate)",
        ],
        technologies: [
          "Meta Business Suite",
          "TikTok Ads Manager",
          "LinkedIn Campaign Manager",
          "Meta Pixel",
          "CAPI",
          "Canva / Adobe CC",
          "Supermetrics",
        ],
        process: [
          "Account Audit",
          "Audience Research",
          "Creative Strategy",
          "Campaign Build",
          "Launch & Test",
          "Optimization",
          "Reporting",
        ],
        targetAudience:
          "B2C and B2B businesses needing cost-efficient lead generation and brand awareness campaigns across social platforms in UAE/GCC.",
      },
      {
        slug: "email-marketing",
        name: "Email Marketing & Automation",
        tagline: "Automated nurture sequences that convert leads into revenue",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Mail",
        color: "#c9a44c",
        overview:
          "Strategic email marketing with automated lifecycle sequences — from welcome series to re-engagement campaigns. CRM-integrated with behavioral triggers, segmentation, and advanced personalization. Arabic & English bilingual campaigns for UAE audiences.",
        features: [
          "Email strategy & campaign planning",
          "Custom responsive email template design",
          "Automated welcome & onboarding sequences",
          "Lead nurturing drip campaigns",
          "Behavioral trigger-based automation",
          "List segmentation & personalization",
          "A/B testing (subject, content, timing)",
          "CRM integration (Odoo, HubSpot, Klaviyo)",
          "Deliverability optimization",
          "Analytics & conversion reporting",
        ],
        technologies: [
          "Klaviyo",
          "Mailchimp",
          "HubSpot",
          "Odoo Email",
          "Beehiiv",
          "Figma / MJML",
          "Litmus",
        ],
        process: [
          "List Audit",
          "Strategy",
          "Template Design",
          "Sequence Build",
          "Integration",
          "Testing",
          "Launch & Optimize",
        ],
        targetAudience:
          "eCommerce brands, SaaS companies, and service businesses wanting to automate customer communications and maximize lifetime value.",
      },
      {
        slug: "content-marketing",
        name: "Content Marketing",
        tagline: "Authority-building content that educates and converts",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "PenTool",
        color: "#10b981",
        overview:
          "Strategic content marketing covering blog posts, whitepapers, case studies, infographics, and video scripts. SEO-optimized content in Arabic and English that positions your brand as the go-to authority in your industry while driving organic traffic and lead generation.",
        features: [
          "Content strategy & editorial calendar",
          "SEO-optimized blog articles (AR/EN)",
          "Whitepapers & industry reports",
          "Case study writing & design",
          "Infographic creation",
          "Video script writing",
          "LinkedIn thought leadership content",
          "Content distribution strategy",
          "Lead magnet creation",
          "Content performance analytics",
        ],
        technologies: [
          "Ahrefs / SEMrush",
          "Surfer SEO",
          "Grammarly / ProWritingAid",
          "Canva / Adobe CC",
          "WordPress / Sanity",
          "Notion",
        ],
        process: [
          "Content Audit",
          "Topic Research",
          "Content Calendar",
          "Writing & Design",
          "SEO Optimization",
          "Publishing",
          "Promotion",
        ],
        targetAudience:
          "B2B companies and service businesses wanting to build thought leadership, improve SEO, and generate inbound leads through valuable content.",
      },
      {
        slug: "branding",
        name: "Brand Identity & Graphic Design",
        tagline: "Iconic brand identities that command premium positioning",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Sparkles",
        color: "#c9a44c",
        overview:
          "Full brand identity creation — from logo and visual language to comprehensive brand guidelines. Strategic brand positioning, competitive differentiation, and consistent visual systems across all touchpoints in English and Arabic.",
        features: [
          "Brand strategy & positioning",
          "Logo design & identity system",
          "Color palette & typography system",
          "Brand guidelines document",
          "Business cards & stationery",
          "Marketing collateral design",
          "Social media visual templates",
          "Arabic calligraphy integration",
          "Brand audit & refresh",
          "Environmental & signage design",
        ],
        technologies: [
          "Adobe Illustrator",
          "Adobe Photoshop",
          "Figma",
          "Adobe InDesign",
          "Canva Pro",
          "Midjourney",
        ],
        process: [
          "Brand Discovery",
          "Competitive Analysis",
          "Concept Development",
          "Design Presentation",
          "Refinement",
          "Guidelines Creation",
          "Asset Delivery",
        ],
        targetAudience:
          "Startups launching new brands, established businesses rebranding, or companies needing consistent professional visual identity across all markets.",
      },
      {
        slug: "3d-design",
        name: "3D Design & Visualization",
        tagline: "Photorealistic 3D that sells before products exist",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Box",
        color: "#7b2fff",
        overview:
          "Professional 3D product visualization, architectural renders, and motion graphics for marketing and presentations. Photorealistic imagery that helps customers see and desire products before they're built or launched.",
        features: [
          "3D product modeling & rendering",
          "Architectural & interior visualization",
          "Photorealistic product photography (3D)",
          "Animated product demos (3D)",
          "3D motion graphics for video",
          "Virtual staging for real estate",
          "360° product viewers for eCommerce",
          "CAD to 3D visualization",
          "AR-ready 3D model preparation",
          "Branded 3D illustrations",
        ],
        technologies: [
          "Blender",
          "Cinema 4D",
          "3ds Max",
          "V-Ray / Corona",
          "Adobe After Effects",
          "Unreal Engine",
          "Spline",
        ],
        process: [
          "Brief & References",
          "Modeling",
          "Materials & Texturing",
          "Lighting Setup",
          "Rendering",
          "Post-Production",
          "Delivery",
        ],
        targetAudience:
          "Product companies, real estate developers, furniture brands, and manufacturers needing high-quality 3D visuals for marketing before physical production.",
      },
      {
        slug: "video-production",
        name: "Video Production & Photography",
        tagline: "Cinematic content that captures attention and drives action",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "Video",
        color: "#ef4444",
        overview:
          "Full-service video production and photography — from concept to final delivery. Corporate films, product videos, social media content, event coverage, aerial drone footage, and professional photography for UAE brands.",
        features: [
          "Corporate & brand films",
          "Product demonstration videos",
          "Social media video content",
          "Aerial drone videography & photography",
          "Event & conference coverage",
          "Professional photography (products, team, office)",
          "Animation & motion graphics",
          "Video editing & color grading",
          "Voice-over (Arabic & English)",
          "YouTube channel setup & optimization",
        ],
        technologies: [
          "Sony / Canon Cinema",
          "DJI Drones",
          "Adobe Premiere Pro",
          "After Effects",
          "DaVinci Resolve",
          "Cinema 4D",
        ],
        process: [
          "Brief & Script",
          "Pre-production",
          "Shooting Day",
          "Editing",
          "Color & Sound",
          "Review",
          "Delivery",
        ],
        targetAudience:
          "Businesses wanting professional video content for their website, social media, advertising campaigns, or corporate communications.",
      },
      {
        slug: "cro",
        name: "Conversion Rate Optimization",
        tagline: "More conversions from existing traffic — measurably",
        category: "Digital Marketing & Creative",
        categorySlug: "digital-marketing",
        icon: "TrendingUp",
        color: "#f59e0b",
        overview:
          "Data-driven CRO using heatmaps, session recordings, user testing, and A/B testing to systematically increase conversions from your existing website traffic. We identify friction points and implement evidence-based improvements that lift revenue without increasing ad spend.",
        features: [
          "CRO audit & opportunity identification",
          "Heatmap & session recording analysis",
          "User journey mapping & friction analysis",
          "A/B & multivariate testing",
          "Landing page optimization",
          "Checkout flow optimization",
          "Form optimization",
          "Social proof & trust signal placement",
          "Copy optimization",
          "Conversion funnel analytics",
        ],
        technologies: [
          "Hotjar",
          "Microsoft Clarity",
          "Google Optimize / VWO",
          "Unbounce",
          "GA4",
          "Figma",
          "Crazy Egg",
        ],
        process: [
          "Analytics Audit",
          "Hypothesis Formation",
          "Test Design",
          "Implementation",
          "Testing Period",
          "Analysis",
          "Rollout",
        ],
        targetAudience:
          "eCommerce businesses and lead generation websites with existing traffic wanting to maximize revenue from their current visitor numbers.",
      },
    ],
  },
  {
    slug: "ai-automation",
    name: "AI, Automation & Data",
    shortName: "AI & Automation",
    description:
      "Harness artificial intelligence and intelligent automation to eliminate repetitive work, unlock data insights, and build competitive advantages that compound over time.",
    icon: "Brain",
    color: "#7b2fff",
    services: [
      {
        slug: "ai-consulting",
        name: "AI Consulting & Strategy",
        tagline: "Practical AI roadmaps that deliver business value",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "Lightbulb",
        color: "#7b2fff",
        overview:
          "Strategic AI consulting that cuts through the hype and identifies real, high-impact AI opportunities in your business. We assess your data maturity, map AI use cases to business outcomes, develop implementation roadmaps, and support change management for AI adoption.",
        features: [
          "AI readiness assessment",
          "Use case identification & prioritization",
          "Data maturity evaluation",
          "AI strategy & roadmap development",
          "Build vs. buy vs. partner analysis",
          "ROI modeling for AI initiatives",
          "AI governance & ethics framework",
          "Change management planning",
          "Vendor selection support",
          "Executive AI literacy workshops",
        ],
        technologies: [
          "OpenAI / Anthropic APIs",
          "Azure AI",
          "AWS AI/ML Services",
          "Google Cloud AI",
          "Power BI",
          "Python",
        ],
        process: [
          "Discovery Workshop",
          "Data Assessment",
          "Use Case Mapping",
          "Roadmap Development",
          "Proof of Concept",
          "Business Case",
          "Implementation Support",
        ],
        targetAudience:
          "C-suite executives and operations leaders wanting to understand where AI creates genuine business value for their specific industry and operational context.",
      },
      {
        slug: "generative-ai",
        name: "Generative AI Solutions",
        tagline: "Custom AI applications powered by LLMs and generative models",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "Cpu",
        color: "#7b2fff",
        overview:
          "Custom generative AI applications built on GPT-4, Claude, Gemini, and open-source LLMs. RAG (Retrieval-Augmented Generation) systems, AI content pipelines, document intelligence, code generation tools, and AI-powered workflows tailored to your business needs.",
        features: [
          "RAG systems on proprietary documents",
          "Custom GPT & Claude integrations",
          "AI content generation pipelines",
          "Document intelligence & extraction",
          "AI-powered workflow automation",
          "Fine-tuning on domain-specific data",
          "Multi-modal AI (text, image, audio)",
          "AI API integration & management",
          "Prompt engineering & optimization",
          "AI safety & output filtering",
        ],
        technologies: [
          "OpenAI GPT-4o",
          "Anthropic Claude",
          "LangChain / LlamaIndex",
          "Pinecone / Chroma",
          "Python",
          "FastAPI",
          "AWS / Azure",
        ],
        process: [
          "Use Case Definition",
          "Data Preparation",
          "Model Selection",
          "Development",
          "Testing & Safety",
          "Integration",
          "Monitoring",
        ],
        targetAudience:
          "Businesses wanting to leverage cutting-edge AI for competitive advantage — from customer-facing AI features to internal productivity tools.",
      },
      {
        slug: "ai-chatbots",
        name: "AI Chatbot & Virtual Assistant",
        tagline: "24/7 intelligent assistants that handle customer queries at scale",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "MessageSquare",
        color: "#00d4ff",
        overview:
          "Intelligent AI chatbots and virtual assistants trained on your business knowledge base. Arabic and English NLP, multi-channel deployment (website, WhatsApp, mobile app), CRM integration, and seamless human handoff for complex queries.",
        features: [
          "Custom AI chatbot development",
          "Arabic & English NLP",
          "WhatsApp Business API integration",
          "Knowledge base training & RAG",
          "CRM & helpdesk integration",
          "Lead qualification automation",
          "Appointment booking automation",
          "Human agent handoff logic",
          "Sentiment analysis & escalation",
          "Analytics dashboard & conversation logs",
        ],
        technologies: [
          "OpenAI / Anthropic",
          "Dialogflow / Rasa",
          "WhatsApp Cloud API",
          "LangChain",
          "Botpress",
          "Twilio",
          "Node.js / Python",
        ],
        process: [
          "Conversation Design",
          "Knowledge Base Prep",
          "Model Training",
          "Integration",
          "Testing",
          "Deployment",
          "Monitoring & Tuning",
        ],
        targetAudience:
          "Businesses with high customer inquiry volume wanting to reduce support costs, improve response times, and provide 24/7 assistance in Arabic and English.",
      },
      {
        slug: "rpa",
        name: "Robotic Process Automation (RPA)",
        tagline: "Eliminate manual data work with intelligent automation bots",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "Bot",
        color: "#00e68a",
        overview:
          "RPA implementation that automates repetitive manual processes — data entry, document processing, report generation, system integrations, and cross-application workflows. Attended and unattended bots that work 24/7 with 100% accuracy.",
        features: [
          "Process discovery & automation mapping",
          "Attended & unattended RPA bots",
          "Document processing automation",
          "Data entry & migration automation",
          "Report generation & distribution",
          "Cross-system data synchronization",
          "Exception handling & alerting",
          "Bot performance monitoring",
          "RPA CoE setup & governance",
          "Hyperautomation with AI/ML",
        ],
        technologies: [
          "UiPath",
          "Automation Anywhere",
          "Power Automate",
          "Blue Prism",
          "Python",
          "Selenium",
          "OCR (ABBYY / Azure Form Recognizer)",
        ],
        process: [
          "Process Assessment",
          "ROI Analysis",
          "Bot Design",
          "Development",
          "Testing",
          "Deployment",
          "Monitoring & Maintenance",
        ],
        targetAudience:
          "Operations-heavy businesses with high volumes of manual, rule-based work in finance, HR, procurement, logistics, or data management.",
      },
      {
        slug: "business-intelligence",
        name: "Business Intelligence & Data Analytics",
        tagline: "Real-time dashboards that turn data into decisions",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "BarChart2",
        color: "#f59e0b",
        overview:
          "End-to-end BI implementation — from data warehouse design and ETL pipeline development to interactive Power BI, Tableau, or custom dashboards. Transform siloed data into unified business intelligence that drives better decisions faster.",
        features: [
          "Data warehouse design & implementation",
          "ETL / ELT pipeline development",
          "Power BI / Tableau dashboard development",
          "Custom real-time analytics dashboards",
          "KPI definition & tracking framework",
          "Data quality & governance",
          "Self-service analytics enablement",
          "Automated report distribution",
          "Cross-system data consolidation",
          "Executive dashboard development",
        ],
        technologies: [
          "Power BI",
          "Tableau",
          "dbt",
          "Apache Airflow",
          "Snowflake / BigQuery",
          "Python / SQL",
          "Azure Data Factory",
        ],
        process: [
          "Data Audit",
          "Requirements",
          "Data Architecture",
          "ETL Development",
          "Dashboard Design",
          "Testing",
          "Training & Rollout",
        ],
        targetAudience:
          "Businesses whose decision-making is slowed by manual reporting, siloed data, or lack of real-time visibility into operational and financial performance.",
      },
      {
        slug: "machine-learning",
        name: "Machine Learning & Predictive Analytics",
        tagline: "Predictive models that see what's coming before it arrives",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "Activity",
        color: "#7b2fff",
        overview:
          "Custom machine learning models for demand forecasting, churn prediction, recommendation engines, fraud detection, and predictive maintenance. From data preparation to model deployment and monitoring in production.",
        features: [
          "Demand & sales forecasting models",
          "Customer churn prediction",
          "Recommendation engine development",
          "Fraud detection & anomaly detection",
          "Predictive maintenance models",
          "Customer lifetime value prediction",
          "Price optimization models",
          "Natural language classification",
          "MLOps pipeline implementation",
          "Model monitoring & drift detection",
        ],
        technologies: [
          "Python (scikit-learn, XGBoost)",
          "TensorFlow / PyTorch",
          "MLflow",
          "Azure ML / AWS SageMaker",
          "Databricks",
          "FastAPI",
          "Docker",
        ],
        process: [
          "Problem Definition",
          "Data Collection",
          "Feature Engineering",
          "Model Development",
          "Validation",
          "Deployment",
          "Monitoring",
        ],
        targetAudience:
          "Data-rich businesses wanting to use their historical data to predict future outcomes and automate intelligent decision-making.",
      },
      {
        slug: "nlp",
        name: "Natural Language Processing (NLP)",
        tagline: "Make machines understand and generate human language",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "Languages",
        color: "#00d4ff",
        overview:
          "Custom NLP solutions for Arabic and English text — sentiment analysis, entity extraction, document classification, automated summarization, and multilingual content processing at scale. Specialized Arabic NLP capabilities for UAE and GCC markets.",
        features: [
          "Arabic & English sentiment analysis",
          "Named entity recognition (NER)",
          "Document classification & routing",
          "Automated document summarization",
          "Contract & legal document analysis",
          "Customer feedback analysis at scale",
          "Multilingual text processing",
          "Speech-to-text (Arabic/English)",
          "Text generation & rewriting",
          "Brand mention monitoring",
        ],
        technologies: [
          "BERT / AraBERT",
          "spaCy",
          "Hugging Face Transformers",
          "OpenAI API",
          "Azure Cognitive Services",
          "Python",
          "FastAPI",
        ],
        process: [
          "Use Case Definition",
          "Data Labeling",
          "Model Training",
          "Evaluation",
          "API Development",
          "Integration",
          "Monitoring",
        ],
        targetAudience:
          "Organizations processing large volumes of Arabic or English text — contracts, customer feedback, social media, support tickets, or legal documents.",
      },
      {
        slug: "iot",
        name: "IoT & Smart Solutions",
        tagline: "Connected devices and real-time operational intelligence",
        category: "AI, Automation & Data",
        categorySlug: "ai-automation",
        icon: "Wifi",
        color: "#00e68a",
        overview:
          "End-to-end IoT solutions — from sensor selection and connectivity architecture to cloud data platforms and intelligent dashboards. Smart building systems, industrial IoT, asset tracking, and predictive maintenance for UAE businesses.",
        features: [
          "IoT architecture design & consulting",
          "Sensor selection & hardware integration",
          "Edge computing & gateway setup",
          "Cloud IoT platform (AWS IoT, Azure IoT)",
          "Real-time data dashboards",
          "Predictive maintenance systems",
          "Asset tracking & fleet monitoring",
          "Smart building management systems",
          "Alert & automated response systems",
          "AI-powered anomaly detection",
        ],
        technologies: [
          "MQTT / CoAP",
          "AWS IoT Core",
          "Azure IoT Hub",
          "Raspberry Pi / Arduino",
          "Node-RED",
          "InfluxDB",
          "Grafana",
        ],
        process: [
          "Use Case Discovery",
          "Architecture Design",
          "Hardware Procurement",
          "Connectivity Setup",
          "Platform Development",
          "Testing",
          "Deployment & Monitoring",
        ],
        targetAudience:
          "Industrial companies, logistics operators, facility managers, and smart building developers wanting real-time operational visibility and automation.",
      },
    ],
  },
  {
    slug: "it-infrastructure",
    name: "IT Infrastructure & Managed Services",
    shortName: "Infrastructure",
    description:
      "Enterprise-grade IT infrastructure, cybersecurity, and 24/7 managed services that keep your business running at peak performance with zero compromise on security.",
    icon: "Server",
    color: "#ff6b35",
    services: [
      {
        slug: "it-consulting",
        name: "IT Consultation & Strategy",
        tagline: "Technology roadmaps aligned to your business objectives",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "Compass",
        color: "#ff6b35",
        overview:
          "Strategic IT consulting that aligns technology investments with business objectives. Technology audits, digital transformation roadmaps, IT governance frameworks, vendor management, and budget planning for UAE organizations.",
        features: [
          "IT infrastructure assessment & audit",
          "Digital transformation roadmap",
          "IT strategy & governance framework",
          "Technology vendor evaluation",
          "IT budget planning & optimization",
          "ITIL process assessment",
          "Cloud readiness assessment",
          "Risk assessment & mitigation planning",
          "IT policy & procedure development",
          "CTO-as-a-Service",
        ],
        technologies: [
          "ITIL v4",
          "TOGAF",
          "COBIT",
          "Microsoft 365",
          "Azure / AWS",
          "ServiceNow",
          "Jira Service Management",
        ],
        process: [
          "IT Discovery",
          "Assessment",
          "Strategy Development",
          "Roadmap Creation",
          "Presentation",
          "Implementation Support",
          "Review",
        ],
        targetAudience:
          "CEOs, CFOs, and COOs wanting expert technology strategy without a full-time CTO, or organizations planning major IT transformation initiatives.",
      },
      {
        slug: "networking",
        name: "Networking Solutions",
        tagline: "High-performance enterprise networks designed for reliability",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "Network",
        color: "#3b82f6",
        overview:
          "Complete enterprise networking solutions — LAN/WAN design, WiFi 6 deployment, SD-WAN implementation, firewall configuration, VPN setup, and network monitoring. Cisco, Fortinet, and HPE certified engineers delivering enterprise-grade reliability.",
        features: [
          "LAN / WAN design & implementation",
          "WiFi 6 / 6E enterprise deployment",
          "SD-WAN implementation & management",
          "Next-gen firewall configuration (Fortinet, Cisco)",
          "VPN setup (site-to-site & remote access)",
          "Network segmentation & VLANs",
          "QoS configuration for voice & video",
          "Network performance monitoring",
          "Wireless site surveys",
          "Network documentation & diagrams",
        ],
        technologies: [
          "Cisco",
          "Fortinet",
          "HPE Aruba",
          "Juniper",
          "pfSense",
          "Palo Alto",
          "SolarWinds",
        ],
        process: [
          "Network Assessment",
          "Design",
          "Hardware Procurement",
          "Implementation",
          "Testing",
          "Documentation",
          "Ongoing Monitoring",
        ],
        targetAudience:
          "Businesses building new offices, expanding locations, experiencing network performance issues, or requiring secure remote access infrastructure.",
      },
      {
        slug: "servers-datacenter",
        name: "Server & Data Center Solutions",
        tagline: "Enterprise compute and storage built for UAE data residency",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "HardDrive",
        color: "#6366f1",
        overview:
          "On-premises and hybrid server infrastructure — from rack-and-stack to full data center design. Dell, HPE, and Lenovo server procurement, Windows/Linux server administration, storage solutions, and virtualization. Full compliance with UAE data residency requirements.",
        features: [
          "Server design & procurement (Dell, HPE, Lenovo)",
          "Windows Server & Linux administration",
          "Storage solutions (SAN, NAS, DAS)",
          "Server virtualization (VMware, Hyper-V)",
          "Active Directory & domain services",
          "Backup & disaster recovery",
          "Server hardening & patching",
          "Performance monitoring & capacity planning",
          "Hardware maintenance contracts",
          "UAE data residency compliance",
        ],
        technologies: [
          "Dell PowerEdge",
          "HPE ProLiant",
          "VMware vSphere",
          "Windows Server",
          "Linux (RHEL/Ubuntu)",
          "NetApp / Pure Storage",
          "Veeam",
        ],
        process: [
          "Requirements Assessment",
          "Solution Design",
          "Procurement",
          "Rack & Stack",
          "OS & Software Setup",
          "Testing",
          "Handover & Monitoring",
        ],
        targetAudience:
          "Organizations requiring on-premises or hybrid infrastructure for performance, compliance, data sovereignty, or latency-sensitive workloads.",
      },
      {
        slug: "cloud",
        name: "Cloud Solutions & Migration",
        tagline: "Secure, scalable cloud infrastructure on AWS, Azure & GCP",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "CloudLightning",
        color: "#0ea5e9",
        overview:
          "End-to-end cloud solutions — strategy, architecture, migration, and managed operations on AWS, Microsoft Azure, and Google Cloud. Lift-and-shift, re-platforming, and cloud-native architectures with UAE data residency compliance.",
        features: [
          "Cloud readiness assessment",
          "AWS / Azure / GCP architecture design",
          "Cloud migration (lift-and-shift & re-platform)",
          "Infrastructure as Code (Terraform, Ansible)",
          "Kubernetes & container orchestration",
          "Cloud cost optimization (FinOps)",
          "Cloud security & compliance",
          "Multi-cloud & hybrid cloud setup",
          "DevOps pipeline implementation",
          "24/7 cloud monitoring & management",
        ],
        technologies: [
          "AWS",
          "Microsoft Azure",
          "Google Cloud",
          "Terraform",
          "Kubernetes / Docker",
          "Ansible",
          "Cloudflare",
        ],
        process: [
          "Cloud Assessment",
          "Migration Strategy",
          "Architecture Design",
          "Migration Execution",
          "Testing & Validation",
          "Cutover",
          "Ongoing Management",
        ],
        targetAudience:
          "Organizations migrating from on-premises to cloud, optimizing existing cloud spend, or building cloud-native applications for scalability.",
      },
      {
        slug: "cybersecurity",
        name: "Cybersecurity Services",
        tagline: "Enterprise-grade security that protects what matters most",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "Shield",
        color: "#ef4444",
        overview:
          "Comprehensive cybersecurity services — from penetration testing and vulnerability assessments to 24/7 SOC monitoring, incident response, and compliance (ISO 27001, NESA, UAE NICS). Proactive threat detection using AI-powered security tools.",
        features: [
          "Penetration testing (network, web, mobile)",
          "Vulnerability assessment & management",
          "Security operations center (SOC) monitoring",
          "Incident response & forensics",
          "ISO 27001 implementation & certification support",
          "UAE NESA / NICS compliance",
          "Zero Trust architecture implementation",
          "Email security & anti-phishing",
          "Endpoint detection & response (EDR)",
          "Security awareness training",
        ],
        technologies: [
          "Palo Alto / Fortinet",
          "CrowdStrike",
          "Splunk / Microsoft Sentinel",
          "Tenable / Qualys",
          "Burp Suite",
          "Metasploit",
          "Azure Defender",
        ],
        process: [
          "Security Assessment",
          "Risk Analysis",
          "Remediation Planning",
          "Implementation",
          "Testing",
          "Monitoring Setup",
          "Ongoing Management",
        ],
        targetAudience:
          "Organizations of all sizes needing professional security protection, compliance certification, or incident response capabilities.",
      },
      {
        slug: "itsm",
        name: "IT Service Management (ITSM)",
        tagline: "ITIL-based service management for efficient IT operations",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "ClipboardList",
        color: "#8b5cf6",
        overview:
          "ITIL v4-aligned IT service management implementation using ServiceNow, Jira Service Management, or Freshservice. Incident, problem, change, and asset management workflows that improve IT efficiency and user satisfaction.",
        features: [
          "ServiceNow / Jira SM implementation",
          "Incident management workflows",
          "Problem management process",
          "Change management & CAB setup",
          "Asset & configuration management (CMDB)",
          "Service catalog development",
          "SLA management & reporting",
          "Knowledge base implementation",
          "Self-service portal setup",
          "ITIL v4 process consulting",
        ],
        technologies: [
          "ServiceNow",
          "Jira Service Management",
          "Freshservice",
          "Zendesk",
          "ManageEngine",
          "ITIL v4",
          "Power BI",
        ],
        process: [
          "Process Assessment",
          "Tool Selection",
          "Configuration",
          "Workflow Design",
          "Testing",
          "Training",
          "Go-Live",
        ],
        targetAudience:
          "IT departments wanting to professionalize service delivery, reduce MTTR, improve SLA compliance, and demonstrate value to the business.",
      },
      {
        slug: "procurement",
        name: "IT Procurement & Hardware Supply",
        tagline: "Authorized hardware supply with competitive pricing for UAE",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "ShoppingCart",
        color: "#10b981",
        overview:
          "Authorized IT hardware and software procurement for UAE businesses — laptops, servers, networking equipment, storage, and licensed software. Competitive pricing through direct vendor relationships with Dell, HP, Lenovo, Cisco, and Microsoft.",
        features: [
          "IT hardware procurement (Dell, HP, Lenovo, Cisco)",
          "Authorized software licensing (Microsoft, Adobe)",
          "Hardware specification & recommendation",
          "Competitive pricing & volume discounts",
          "Asset tagging & inventory management",
          "Warranty management & extended support",
          "Hardware disposal & data destruction",
          "Device management (MDM) setup",
          "Hardware-as-a-Service (HaaS) options",
          "Same-day delivery in Dubai",
        ],
        technologies: [
          "Dell",
          "HP / HPE",
          "Lenovo",
          "Cisco",
          "Microsoft",
          "VMware",
          "Veeam",
        ],
        process: [
          "Needs Assessment",
          "Specification",
          "Quotation",
          "Order Processing",
          "Delivery & Installation",
          "Asset Registration",
          "Warranty Tracking",
        ],
        targetAudience:
          "Businesses of all sizes in UAE wanting reliable hardware procurement from a trusted local partner with competitive pricing and professional delivery.",
      },
      {
        slug: "cctv",
        name: "CCTV & Surveillance Systems",
        tagline: "Intelligent IP surveillance for total site security",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "Camera",
        color: "#6b7280",
        overview:
          "Professional IP CCTV and surveillance system design, installation, and management. HD and 4K camera systems, NVR/DVR setup, remote monitoring, access control integration, and AI-powered analytics (facial recognition, crowd detection, license plate recognition).",
        features: [
          "IP CCTV design & installation",
          "4K & HD camera systems (Hikvision, Dahua, Axis)",
          "NVR / DVR setup & configuration",
          "Remote monitoring via mobile & web",
          "Access control integration",
          "AI analytics (facial recognition, LPR)",
          "Intercom & video door entry",
          "Cloud storage & backup",
          "Preventive maintenance contracts",
          "Municipality permit assistance (Dubai)",
        ],
        technologies: [
          "Hikvision",
          "Dahua",
          "Axis",
          "Milestone XProtect",
          "Genetec",
          "Suprema Access Control",
          "PoE Switches",
        ],
        process: [
          "Site Survey",
          "System Design",
          "Equipment Procurement",
          "Installation",
          "Configuration & Testing",
          "Training",
          "Maintenance",
        ],
        targetAudience:
          "Offices, retail stores, warehouses, construction sites, and residential buildings requiring professional surveillance and access control.",
      },
      {
        slug: "managed-services",
        name: "Managed IT Services 24/7",
        tagline: "Proactive IT management so you can focus on your business",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "Headphones",
        color: "#00d4ff",
        overview:
          "Comprehensive managed IT services with 24/7 monitoring, proactive maintenance, and guaranteed SLAs. Your entire IT infrastructure managed by our certified team — from helpdesk support to network monitoring, security patching, and vendor management.",
        features: [
          "24/7 infrastructure monitoring & alerting",
          "Helpdesk (L1/L2/L3) with SLA guarantee",
          "Proactive patching & maintenance",
          "Backup monitoring & restore testing",
          "Security event monitoring",
          "Network & server performance management",
          "Vendor management on your behalf",
          "Monthly IT health reports",
          "On-site & remote support",
          "Dedicated account manager",
        ],
        technologies: [
          "N-able / ConnectWise",
          "Veeam Backup",
          "SolarWinds",
          "Microsoft Defender",
          "Freshservice",
          "TeamViewer",
          "Azure Monitor",
        ],
        process: [
          "IT Onboarding Assessment",
          "Monitoring Setup",
          "Documentation",
          "SLA Agreement",
          "Ongoing Monitoring",
          "Monthly Reporting",
          "Quarterly Review",
        ],
        targetAudience:
          "SMEs (10–500 employees) without in-house IT teams, or larger organizations wanting to supplement internal IT with specialist managed services.",
      },
      {
        slug: "disaster-recovery",
        name: "Disaster Recovery & Business Continuity",
        tagline: "Guaranteed recovery when the unexpected happens",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "RefreshCw",
        color: "#f59e0b",
        overview:
          "Comprehensive disaster recovery planning and implementation — from RTO/RPO analysis to automated failover systems, backup architecture, and tested recovery procedures. ISO 22301 business continuity planning for UAE organizations.",
        features: [
          "Business Impact Analysis (BIA)",
          "RTO / RPO definition & planning",
          "Disaster Recovery Plan (DRP) development",
          "Automated backup implementation (Veeam)",
          "Offsite & cloud backup configuration",
          "Failover testing & DR drills",
          "ISO 22301 BCP development",
          "Replication to secondary site / cloud",
          "Recovery runbook documentation",
          "Annual DR test & report",
        ],
        technologies: [
          "Veeam",
          "Zerto",
          "Azure Site Recovery",
          "AWS DR",
          "Veritas",
          "Commvault",
          "VMware SRM",
        ],
        process: [
          "BIA Workshop",
          "Risk Assessment",
          "Strategy Design",
          "Backup Implementation",
          "DR Site Setup",
          "Testing",
          "Documentation & Training",
        ],
        targetAudience:
          "Organizations whose operations cannot afford downtime — financial services, healthcare, retail, logistics, and government agencies.",
      },
      {
        slug: "virtualization",
        name: "Virtualization Solutions",
        tagline: "Maximize hardware ROI with enterprise virtualization",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "Layers",
        color: "#6366f1",
        overview:
          "Server and desktop virtualization implementation using VMware vSphere, Microsoft Hyper-V, and Proxmox. VDI solutions, virtual desktop infrastructure, application virtualization, and hybrid cloud integration.",
        features: [
          "VMware vSphere / ESXi implementation",
          "Microsoft Hyper-V deployment",
          "Virtual Desktop Infrastructure (VDI)",
          "VMware Horizon setup",
          "vSAN storage virtualization",
          "vCenter management setup",
          "Live migration & high availability",
          "VM backup & snapshot management",
          "Capacity planning & optimization",
          "VMware to Azure migration",
        ],
        technologies: [
          "VMware vSphere",
          "VMware Horizon",
          "Microsoft Hyper-V",
          "Proxmox",
          "Citrix",
          "Nutanix",
          "Azure VMware Solution",
        ],
        process: [
          "Infrastructure Assessment",
          "Design",
          "VMware License Planning",
          "Implementation",
          "VM Migration",
          "Testing",
          "Training",
        ],
        targetAudience:
          "Organizations wanting to reduce physical server counts, improve resource utilization, and enable flexible remote working with VDI.",
      },
      {
        slug: "structured-cabling",
        name: "Structured Cabling & Office IT Setup",
        tagline: "The physical backbone for high-performance office networks",
        category: "IT Infrastructure & Managed Services",
        categorySlug: "it-infrastructure",
        icon: "Cable",
        color: "#78716c",
        overview:
          "Professional structured cabling, office network setup, and complete IT infrastructure for new office fit-outs. Cat6/Cat6A cabling, fiber optic runs, patch panel installation, rack setup, and end-to-end testing with certification.",
        features: [
          "Cat6 / Cat6A / fiber optic cabling",
          "Patch panel & rack installation",
          "Server room & comms room setup",
          "Cable testing & certification (Fluke)",
          "WiFi access point deployment",
          "IP phone system installation",
          "AV & presentation system integration",
          "Cable management & labeling",
          "TIA-568 / ISO 11801 compliance",
          "Handover documentation",
        ],
        technologies: [
          "Fluke DTX / DSX Cable Analyzers",
          "Cat6A / Fiber",
          "Cisco / Aruba APs",
          "Belden / CommScope",
          "Panduit",
          "AMP Netconnect",
        ],
        process: [
          "Site Survey",
          "Cabling Design",
          "Material Procurement",
          "Installation",
          "Testing & Certification",
          "Documentation",
          "Handover",
        ],
        targetAudience:
          "Businesses fitting out new offices, relocating, or upgrading aging cabling infrastructure to support modern network requirements.",
      },
    ],
  },
  {
    slug: "mobile-apps",
    name: "Mobile App Development",
    shortName: "Mobile Apps",
    description:
      "Native and cross-platform mobile applications that users love — built for iOS and Android with performance, security, and seamless user experience at the core.",
    icon: "Smartphone",
    color: "#00e68a",
    services: [
      {
        slug: "ios",
        name: "iOS App Development",
        tagline: "Premium Swift apps that feel native to the Apple ecosystem",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "Apple",
        color: "#000000",
        overview:
          "Native iOS applications built with Swift and SwiftUI — from concept to App Store submission. Optimal performance, Apple Human Interface Guidelines compliance, and deep integration with iOS features (HealthKit, MapKit, Core Data, Push Notifications, ARKit).",
        features: [
          "Swift / SwiftUI native development",
          "Apple HIG compliant UX design",
          "iOS feature integration (HealthKit, ARKit, etc.)",
          "Core Data & CloudKit",
          "Push notifications & in-app messaging",
          "App Store submission & optimization",
          "iPad universal app support",
          "Sign in with Apple",
          "Apple Pay integration",
          "TestFlight beta testing",
        ],
        technologies: [
          "Swift",
          "SwiftUI",
          "UIKit",
          "Core Data",
          "CloudKit",
          "Xcode",
          "TestFlight",
        ],
        process: [
          "Concept & UX Design",
          "Architecture",
          "Development Sprints",
          "QA Testing",
          "App Store Review",
          "Launch",
          "Maintenance",
        ],
        targetAudience:
          "Businesses targeting Apple users wanting a premium native iOS experience with full access to Apple platform capabilities.",
      },
      {
        slug: "android",
        name: "Android App Development",
        tagline: "Powerful Kotlin apps for the world's largest mobile platform",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "Smartphone",
        color: "#3ddc84",
        overview:
          "Native Android applications built with Kotlin and Jetpack Compose — Material Design 3 compliant, optimized for the fragmented Android device landscape, and integrated with Google services (Maps, Firebase, Play Billing).",
        features: [
          "Kotlin / Jetpack Compose development",
          "Material Design 3 compliance",
          "Google Maps & Location integration",
          "Firebase (Auth, Firestore, Analytics, Push)",
          "Google Pay integration",
          "Offline-first architecture",
          "Google Play Store submission",
          "Android TV & tablet support",
          "Deep link & app link handling",
          "CrashlyticS integration",
        ],
        technologies: [
          "Kotlin",
          "Jetpack Compose",
          "Android SDK",
          "Firebase",
          "Retrofit",
          "Room DB",
          "Hilt DI",
        ],
        process: [
          "UX Design",
          "Architecture",
          "Development",
          "Device Testing",
          "Play Store Submit",
          "Launch",
          "Updates",
        ],
        targetAudience:
          "Businesses wanting to reach Android users — the majority of smartphone users in UAE and the Middle East.",
      },
      {
        slug: "react-native",
        name: "Cross-Platform — React Native",
        tagline: "One codebase, two native apps, full performance",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "Layers",
        color: "#61dafb",
        overview:
          "React Native applications that deliver near-native performance on both iOS and Android from a single codebase. Cost-effective for businesses wanting simultaneous iOS and Android releases with shared business logic and separate native UI components where needed.",
        features: [
          "Single codebase for iOS & Android",
          "Near-native performance",
          "Native module integration",
          "Expo & bare React Native options",
          "Push notifications (Firebase/APNs)",
          "Offline support with sync",
          "OTA updates (CodePush / Expo Updates)",
          "Deep linking",
          "Analytics & crash reporting",
          "App Store + Play Store submission",
        ],
        technologies: [
          "React Native",
          "TypeScript",
          "Expo",
          "Redux / Zustand",
          "React Navigation",
          "Firebase",
          "CodePush",
        ],
        process: [
          "Design",
          "Architecture",
          "Development",
          "iOS & Android QA",
          "Store Submission",
          "Launch",
          "Maintenance",
        ],
        targetAudience:
          "Startups and businesses needing both iOS and Android apps on a budget, or teams with strong React/JavaScript skills wanting to extend to mobile.",
      },
      {
        slug: "flutter",
        name: "Cross-Platform — Flutter",
        tagline: "Beautiful pixel-perfect apps from a single Dart codebase",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "Triangle",
        color: "#54c5f8",
        overview:
          "Flutter applications with custom widget-based UIs that look identical across iOS, Android, web, and desktop. Google's Material Design and Cupertino widgets with smooth 60/120fps animations and native performance.",
        features: [
          "iOS & Android from single codebase",
          "Custom widget development",
          "60/120fps smooth animations",
          "Material Design & Cupertino widgets",
          "Flutter Web & desktop (optional)",
          "Firebase integration",
          "BLoC / Riverpod state management",
          "Platform channels for native features",
          "Offline-first with Hive / Isar",
          "CI/CD pipeline (Codemagic)",
        ],
        technologies: [
          "Flutter",
          "Dart",
          "Firebase",
          "BLoC / Riverpod",
          "Dio / Retrofit",
          "Hive / Isar",
          "Codemagic",
        ],
        process: [
          "Design",
          "Architecture",
          "Development",
          "Testing",
          "Store Submission",
          "Launch",
          "Support",
        ],
        targetAudience:
          "Businesses wanting highly customized UI with pixel-perfect design control across platforms, or teams needing rapid development with consistent visuals.",
      },
      {
        slug: "pwa",
        name: "Progressive Web Apps (PWA)",
        tagline: "App-like experiences delivered through the browser",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "Globe",
        color: "#5a0fc8",
        overview:
          "Progressive Web Applications that combine web accessibility with app-like features — offline support, push notifications, home screen installation, and fast performance. No app store required, yet delivers mobile-app quality experience.",
        features: [
          "Installable PWA (Add to Home Screen)",
          "Offline support with Service Workers",
          "Push notifications via Web Push API",
          "App Shell architecture",
          "Background sync",
          "Camera & device API access",
          "iOS & Android home screen icon",
          "99+ Lighthouse PWA score",
          "HTTPS & security implementation",
          "App manifest configuration",
        ],
        technologies: [
          "Next.js",
          "Service Workers",
          "Web Push API",
          "IndexedDB / Cache API",
          "Workbox",
          "TypeScript",
          "Vercel",
        ],
        process: [
          "Requirements",
          "Architecture",
          "Development",
          "Offline Strategy",
          "Performance Testing",
          "Launch",
          "Monitoring",
        ],
        targetAudience:
          "Businesses wanting app-like experience without app store friction, or wanting to enhance existing websites with mobile app capabilities.",
      },
      {
        slug: "maintenance",
        name: "App Maintenance & Support",
        tagline: "Keep your app current, secure, and performing",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "Wrench",
        color: "#6b7280",
        overview:
          "Ongoing mobile app maintenance — OS version updates, security patches, new feature development, performance optimization, crash fixes, and app store compliance updates. Monthly retainer plans for peace of mind.",
        features: [
          "iOS & Android OS update compatibility",
          "Security vulnerability patching",
          "Performance monitoring & optimization",
          "Crash fix & debugging",
          "New feature additions",
          "Third-party SDK updates",
          "App Store & Play Store submissions",
          "API integration updates",
          "Analytics & reporting",
          "24/7 emergency support (critical tier)",
        ],
        technologies: [
          "Firebase Crashlytics",
          "Sentry",
          "App Store Connect",
          "Google Play Console",
          "Fastlane",
          "TestFlight",
          "GitHub Actions",
        ],
        process: [
          "App Audit",
          "Maintenance Plan",
          "Monitoring Setup",
          "Monthly Updates",
          "Emergency Response",
          "Quarterly Review",
          "Roadmap Planning",
        ],
        targetAudience:
          "Businesses with existing apps needing ongoing technical maintenance, feature updates, and OS compatibility without a full-time development team.",
      },
      {
        slug: "aso",
        name: "App Store Optimization (ASO)",
        tagline: "More organic downloads from App Store and Google Play",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "TrendingUp",
        color: "#f59e0b",
        overview:
          "Data-driven App Store Optimization for App Store and Google Play — keyword research, metadata optimization, screenshot and preview video creation, rating & review management, and A/B testing to maximize organic downloads.",
        features: [
          "App Store & Google Play keyword research",
          "Title, subtitle & description optimization",
          "Screenshot & preview video creation",
          "App icon A/B testing",
          "Localization (Arabic, English, + more)",
          "Rating & review response management",
          "Competitor analysis",
          "Store listing A/B testing (Play Console)",
          "Featured placement optimization",
          "Monthly performance reporting",
        ],
        technologies: [
          "AppFollow",
          "MobileAction",
          "Sensor Tower",
          "App Store Connect",
          "Google Play Console",
          "Figma",
          "Adobe CC",
        ],
        process: [
          "Store Audit",
          "Keyword Research",
          "Metadata Creation",
          "Visual Assets",
          "Implementation",
          "A/B Testing",
          "Monthly Reporting",
        ],
        targetAudience:
          "App developers and businesses wanting to increase organic downloads and reduce customer acquisition cost through store optimization.",
      },
      {
        slug: "enterprise",
        name: "Enterprise Mobile Solutions",
        tagline: "Secure, integrated mobile apps for enterprise operations",
        category: "Mobile App Development",
        categorySlug: "mobile-apps",
        icon: "Building2",
        color: "#6366f1",
        overview:
          "Enterprise-grade mobile applications for field operations, internal tools, mobile ERP, warehouse management, inspection apps, and employee portals. Built with enterprise security, MDM integration, and ERP connectivity.",
        features: [
          "Mobile ERP & CRM frontends",
          "Field service & inspection apps",
          "Warehouse management apps",
          "Employee self-service mobile portal",
          "MDM integration (Intune, Jamf)",
          "Enterprise SSO (SAML, OAuth)",
          "Offline-first with conflict resolution",
          "Barcode & QR code scanning",
          "Digital forms & approvals",
          "Real-time ERP data sync",
        ],
        technologies: [
          "React Native / Flutter",
          "Microsoft Intune",
          "Azure AD / SAML",
          "Odoo / SAP Mobile SDK",
          "Realm / SQLite",
          "BLE / NFC",
          "REST / GraphQL APIs",
        ],
        process: [
          "Enterprise Requirements",
          "Security Architecture",
          "Design",
          "Development",
          "MDM Integration",
          "UAT",
          "Rollout & Training",
        ],
        targetAudience:
          "Enterprises needing mobile extensions to their ERP, field operations apps, or internal workflow tools with enterprise security and compliance.",
      },
    ],
  },
];

export const allServices: Service[] = serviceCategories.flatMap(
  (cat) => cat.services
);

export function getServiceBySlug(categorySlug: string, serviceSlug: string) {
  const category = serviceCategories.find((c) => c.slug === categorySlug);
  return category?.services.find((s) => s.slug === serviceSlug);
}

export function getCategoryBySlug(slug: string) {
  return serviceCategories.find((c) => c.slug === slug);
}
