import { notFound } from "next/navigation";
import { serviceCategories } from "@/lib/services-data";
import IndustryPageClient from "@/components/industries/IndustryPageClient";
import type { Metadata } from "next";

interface Props { params: Promise<{ slug: string }>; }

const industryData: Record<string, { name: string; icon: string; desc: string; challenges: string[]; solutions: string[]; color: string; relatedServices: string[] }> = {
  "real-estate": { name: "Real Estate & Property", icon: "🏗️", color: "#00d4ff", desc: "From Dubai developers managing 20 projects to individual agents, we deliver technology that drives deals, automates operations, and satisfies investors.", challenges: ["Fragmented data across multiple projects and subsidiaries", "Manual financial reporting and VAT compliance", "Poor CRM and lead management from portals", "No unified view of inventory, bookings, and payments"], solutions: ["Odoo ERP for multi-company real estate operations", "CRM with portal integrations (Property Finder, Bayut, Dubizzle)", "Customer portals for payment tracking and document management", "BI dashboards for CEO/CFO real-time visibility"], relatedServices: ["odoo-implementation", "odoo-crm", "custom-erp"] },
  "healthcare": { name: "Healthcare", icon: "🏥", color: "#00e68a", desc: "HAAD/DHA-compliant digital transformation for hospitals, clinics, and healthcare groups — from patient management to AI diagnostics.", challenges: ["Paper-based patient records and manual appointment booking", "Compliance with HAAD, DHA, and DoH regulations", "Billing complexity with insurance and cash patients", "Lack of clinical and operational KPI visibility"], solutions: ["Electronic health records (EHR) implementation", "HAAD/DHA-compliant billing and claims management", "Patient engagement portals and mobile apps", "AI-powered diagnostic assistance and scheduling optimization"], relatedServices: ["ai-consulting", "ai-chatbots", "custom-erp"] },
  "retail": { name: "Retail & eCommerce", icon: "🛍️", color: "#7b2fff", desc: "From Shopify Plus stores to omnichannel retail management — we help UAE retailers sell more, lose less, and grow faster.", challenges: ["Inventory sync between online and physical stores", "Arabic/English bilingual customer experience", "UAE-specific payment gateways and BNPL (Tabby, Tamara)", "Low conversion rates on mobile"], solutions: ["Shopify Plus or headless commerce implementation", "Odoo inventory + eCommerce integration", "UAE payment gateway setup (Network International, Stripe, Tabby)", "CRO and UX optimization"], relatedServices: ["shopify-development", "odoo-implementation", "custom-websites"] },
  "hospitality": { name: "F&B & Hospitality", icon: "🍽️", color: "#c9a44c", desc: "Technology for restaurants, hotels, and hospitality groups — from multi-branch POS to online ordering and loyalty programs.", challenges: ["Manual order and inventory management across branches", "No real-time sales visibility or food waste tracking", "Disconnected delivery integrations (Talabat, Careem)", "Staff scheduling and payroll complexity"], solutions: ["POS integration and multi-branch management", "Odoo for F&B inventory, purchasing, and operations", "Delivery platform integrations (Talabat, Noon Food, Careem)", "Loyalty program and customer app development"], relatedServices: ["odoo-implementation", "mobile-apps", "custom-websites"] },
  "government": { name: "Government & Public Sector", icon: "🏛️", color: "#0066ff", desc: "Digital transformation solutions aligned with UAE Vision 2031 — e-government portals, smart city systems, and citizen services.", challenges: ["Legacy systems and paper-based processes", "Compliance with UAE government digital standards", "Multi-department integration complexity", "Citizen experience expectations"], solutions: ["E-government portal development", "Document management and workflow automation", "Cybersecurity and data residency compliance", "Smart city IoT integrations"], relatedServices: ["custom-erp", "cybersecurity", "iot"] },
  "legal": { name: "Legal & Professional Services", icon: "⚖️", color: "#ff4d6a", desc: "Case management, billing automation, and client portals for law firms and professional service organizations in the UAE.", challenges: ["Time tracking and billing complexity", "Document version control and confidentiality", "Client communication and portal access", "WPS payroll compliance"], solutions: ["Legal case management system implementation", "Billing and time-tracking automation", "Secure client portals with document sharing", "HR and payroll with UAE labor law compliance"], relatedServices: ["odoo-hcm", "custom-erp", "custom-websites"] },
  "education": { name: "Education & Training", icon: "🎓", color: "#00d4ff", desc: "LMS platforms, student management systems, and digital learning infrastructure for schools, universities, and training centers.", challenges: ["Manual student lifecycle management", "Online learning platform gaps post-COVID", "Fee management and parent portals", "HR compliance for teaching staff"], solutions: ["Learning Management System (LMS) deployment", "Student Information System (SIS) implementation", "Parent and student portals", "Digital marketing for enrollment growth"], relatedServices: ["custom-erp", "odoo-hcm", "custom-websites"] },
  "oil-gas": { name: "Oil & Gas", icon: "⚡", color: "#c9a44c", desc: "Asset management, HSE compliance, field operations technology, and supply chain systems for oil, gas, and energy companies in the UAE.", challenges: ["Asset maintenance tracking and downtime", "HSE compliance documentation", "Remote field operations coordination", "Complex procurement and contractor management"], solutions: ["Asset management and preventive maintenance systems", "HSE compliance tracking and reporting", "Field operations mobile apps", "Procurement and supplier management (ERP)"], relatedServices: ["custom-erp", "iot", "mobile-apps"] },
  "logistics": { name: "Logistics & Supply Chain", icon: "🚚", color: "#00e68a", desc: "Fleet management, warehouse management, last-mile delivery, and supply chain visibility for logistics operators across the UAE and GCC.", challenges: ["Fleet tracking and driver management", "Warehouse inventory accuracy", "Customer delivery visibility and communication", "Route optimization and fuel cost control"], solutions: ["Fleet management system with real-time GPS tracking", "Warehouse Management System (WMS)", "Customer delivery tracking portal", "Route optimization with AI"], relatedServices: ["custom-erp", "iot", "mobile-apps"] },
  "finance": { name: "Finance & Banking", icon: "🏦", color: "#0066ff", desc: "Fintech solutions, compliance systems, and digital transformation for financial institutions operating under CBUAE regulations.", challenges: ["CBUAE regulatory compliance", "Legacy core banking system modernization", "Digital customer experience expectations", "Fraud detection and AML compliance"], solutions: ["Digital banking and fintech app development", "AI fraud detection and AML systems", "Customer onboarding portal with KYC", "Business intelligence for financial reporting"], relatedServices: ["ai-machine-learning", "custom-erp", "mobile-apps"] },
  "construction": { name: "Construction", icon: "🏗️", color: "#7b2fff", desc: "Project management, procurement, subcontractor management, and financial control for construction and contracting companies.", challenges: ["Project cost overruns and tracking", "Subcontractor management and payments", "Procurement and material management", "Site reporting and documentation"], solutions: ["Construction ERP (Odoo or custom)", "Subcontractor portal and payment automation", "Document management and site reporting apps", "Project management dashboards"], relatedServices: ["odoo-implementation", "custom-erp", "mobile-apps"] },
  "manufacturing": { name: "Manufacturing", icon: "🏭", color: "#ff4d6a", desc: "MRP, quality control, maintenance scheduling, and supply chain technology for UAE and GCC manufacturers.", challenges: ["Production planning and scheduling", "Quality control and defect tracking", "Maintenance and downtime management", "Supply chain visibility"], solutions: ["Manufacturing ERP with MRP/MES modules", "Quality management system", "Preventive maintenance scheduling", "Supply chain analytics and forecasting"], relatedServices: ["odoo-implementation", "business-intelligence", "iot"] },
};

export async function generateStaticParams() {
  return Object.keys(industryData).map(slug => ({ slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const ind = industryData[slug];
  if (!ind) return { title: "Not Found" };
  return { title: `${ind.name} IT Solutions Dubai | Quvex Technologies`, description: ind.desc };
}

export default async function IndustryPage({ params }: Props) {
  const { slug } = await params;
  const ind = industryData[slug];
  if (!ind) notFound();

  const allServices = serviceCategories.flatMap(c => c.services.map(s => ({ ...s, categorySlug: c.slug })));
  const relatedServices = allServices.filter(s => ind.relatedServices.includes(s.slug));

  return <IndustryPageClient slug={slug} ind={ind} relatedServices={relatedServices} />;
}
